"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowLeft, Megaphone, Shield, Users, Wrench, Settings } from "lucide-react";

const tools=["Prank simulations","Desktop experiences","Cyber terminal","Matrix effects","Retro browser"];
export default function AdminControl(){
 const [notice,setNotice]=useState(""); const [saved,setSaved]=useState(false);
 return <main className="adminControl"><header><Link href="/admin"><ArrowLeft size={17}/> ADMIN CONTROL</Link><span>VIP / CONTROL CENTER</span></header><section className="hero"><small>SECURE CONSOLE</small><h1>Control Center</h1><p>Manage the experience, content and moderation from one responsive panel.</p></section><div className="grid"><section className="card"><div className="title"><Wrench/> <b>Experience</b></div>{tools.map(x=><label key={x}><span>{x}</span><input type="checkbox" defaultChecked/></label>)}</section><section className="card"><div className="title"><Megaphone/> <b>Announcement</b></div><input value={notice} onChange={e=>setNotice(e.target.value)} placeholder="Write an announcement..."/><button onClick={()=>setSaved(true)}>{saved?"Saved ✓":"Publish"}</button></section><section className="card"><div className="title"><Shield/> <b>Moderation</b></div><p>Reports, blocks and user safety controls are protected by Supabase RLS.</p><Link href="/admin/activity">Open audit logs →</Link></section><section className="card"><div className="title"><Users/> <b>Community</b></div><p>Manage users, categories and Nexuses from the admin dashboard.</p></section><section className="card"><div className="title"><Settings/> <b>Developer</b></div><p>Somesh Koli · @offx.somesh · @developer.somesh</p><p>someshkoli442288@gmail.com</p><Link href="/developer">View developer page →</Link></section></div><style jsx>{`.adminControl{min-height:100vh;background:#020602;color:#39ff14;padding:0 6vw 70px;font-family:ui-monospace,monospace}.adminControl header{height:68px;border-bottom:1px solid #124512;display:flex;align-items:center;justify-content:space-between}.adminControl header a{color:#39ff14;text-decoration:none;display:flex;gap:8px;align-items:center}.adminControl header span{font-size:10px;opacity:.65}.hero{padding:9vh 0 5vh}.hero small{letter-spacing:3px;opacity:.6}.hero h1{font-size:clamp(42px,7vw,78px);margin:12px 0}.hero p{color:#9be890}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;max-width:1050px}.card{border:1px solid #155915;background:#030903;padding:22px;display:flex;flex-direction:column;gap:14px}.title{display:flex;align-items:center;gap:10px}.title svg{width:19px}.card label{display:flex;justify-content:space-between;border-top:1px solid #0b310b;padding-top:12px;font-size:12px}.card input:not([type=checkbox]){background:#000;border:1px solid #176317;color:#39ff14;padding:12px;font:inherit}.card button{background:#39ff14;color:#001000;border:0;padding:11px;font:inherit;font-weight:800;cursor:pointer}.card p{color:#8dd984;font-size:12px;line-height:1.6;margin:0}.card a{color:#39ff14;font-size:12px}@media(max-width:700px){.adminControl{padding:0 16px 50px}.grid{grid-template-columns:1fr}.hero{padding:7vh 0 4vh}.adminControl header span{display:none}}`}</style></main>
}
