"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { ArrowRight,Eye,EyeOff,LockKeyhole,Mail,UserRound } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function AuthPage(){
 const [signup,setSignup]=useState(false),[show,setShow]=useState(false),[name,setName]=useState(""),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{const mode=new URLSearchParams(location.search).get("mode");if(mode==="signup")setSignup(true);createClient().auth.getSession().then(({data})=>{if(data.session)location.href="/dashboard"})},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);setMessage("");const supabase=createClient();if(signup){const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)setMessage(error.message);else setMessage("Account created. Check your email if confirmation is enabled.")}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message);else location.href="/dashboard"}setLoading(false)}
 return <main className="cx-auth"><div className="cx-auth-bg"/><header className="cx-auth-nav"><Link href="/" className="cx-brand"><img src="/createx-logo.svg" alt=""/><span>CreateX <b>AI</b></span></Link><Link href="/developer" className="cx-auth-dev">Built by Somesh Koli <ArrowRight size={13}/></Link></header><div className="cx-auth-grid"><section className="cx-auth-story"><div className="cx-live"><i/> YOUR CREATIVE WORKSPACE</div><h1>Make the<br/><span>next thing.</span></h1><p>Sign in or create your free account to generate, chat, code and keep your work in one place.</p><div className="cx-auth-stats"><span><b>10</b> images / day</span><span><b>10</b> videos / day</span><span><b>∞</b> chat</span></div></section><section className="cx-auth-card"><div className="cx-auth-card-head"><span className="cx-auth-kicker">{signup?"NEW ACCOUNT":"WELCOME BACK"}</span><h2>{signup?"Start creating.":"Continue creating."}</h2><p>{signup?"Your CreateX AI workspace starts here.":"Access your studio and private creations."}</p></div><form onSubmit={submit}>{signup&&<label><UserRound size={16}/><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label>}<label><Mail size={16}/><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address"/></label><label><LockKeyhole size={16}/><input required minLength={6} type={show?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={16}/>:<Eye size={16}/>}</button></label><button className="cx-auth-submit" disabled={loading}>{loading?"Please wait…":signup?"Create account":"Sign in"}<ArrowRight size={16}/></button></form>{message&&<div className="cx-auth-message">{message}</div>}<div className="cx-auth-switch">{signup?"Already have an account?":"New to CreateX AI?"} <button onClick={()=>{setSignup(!signup);setMessage("")}}>{signup?"Sign in":"Create account"}</button></div><div className="cx-auth-note">Free access · no credits · no payment required</div></section></div></main>;
}