"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowRight, BarChart3, Clapperboard, Image as ImageIcon, LogOut, MessageCircle, Sparkles, WandSparkles } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

type Creation={type:"image"|"video"};
type Usage={images_used:number;images_remaining:number;videos_used:number;videos_remaining:number;chat_unlimited:boolean};

export default function DashboardPage(){
 const [email,setEmail]=useState(""); const [name,setName]=useState("Creator");
 const [usage,setUsage]=useState<Usage>({images_used:0,images_remaining:10,videos_used:0,videos_remaining:10,chat_unlimited:true});
 const [counts,setCounts]=useState({image:0,video:0}); const [loading,setLoading]=useState(true);
 useEffect(()=>{const supabase=createClient(); (async()=>{const {data:{user}}=await supabase.auth.getUser(); if(!user){location.href="/auth";return;} setEmail(user.email??"");setName(user.user_metadata?.full_name||user.email?.split("@")[0]||"Creator"); const [{data:u},{data:c}]=await Promise.all([supabase.rpc("get_createx_daily_usage",{p_user_id:user.id}),supabase.from("createx_generations").select("type").eq("user_id",user.id)]); if(u)setUsage(u as Usage); const rows=(c as Creation[])||[];setCounts({image:rows.filter(x=>x.type==="image").length,video:rows.filter(x=>x.type==="video").length});setLoading(false);})();},[]);
 async function logout(){await createClient().auth.signOut();location.href="/auth"}
 if(loading)return <main className="cx-bg grid min-h-screen place-items-center text-white"><div className="flex items-center gap-3 text-white/45"><Sparkles className="animate-pulse" size={18}/>Loading your studio…</div></main>;
 return <main className="cx-bg min-h-screen pb-24 text-white md:pb-10">
  <nav className="sticky top-0 z-30 border-b border-white/10 bg-[#050507]/80 backdrop-blur-2xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 md:px-8"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-cyan-400 shadow-lg shadow-violet-950/30"><Sparkles size={19}/></span><span className="font-black tracking-tight">CreateX <span className="text-violet-300">AI</span></span></Link><div className="flex items-center gap-2"><Link href="/creations" className="hidden rounded-xl border border-white/10 px-4 py-2 text-sm text-white/50 hover:bg-white/[.05] hover:text-white md:block">My creations</Link><button onClick={logout} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/[.03] px-4 py-2 text-sm text-white/55 hover:bg-white/[.07] hover:text-white"><LogOut size={16}/>Logout</button></div></div></nav>
  <div className="mx-auto max-w-7xl px-5 py-8 md:px-8 md:py-12">
   <div className="relative overflow-hidden rounded-[32px] border border-white/10 bg-white/[.035] p-6 md:p-9"><div className="pointer-events-none absolute -right-24 -top-28 h-64 w-64 rounded-full bg-violet-500/10 blur-3xl"/><div className="relative flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-[10px] font-bold uppercase tracking-[.28em] text-violet-300">Creator dashboard</p><h1 className="mt-2 text-4xl font-black tracking-[-.05em] md:text-6xl">Welcome, {name}.</h1><p className="mt-2 text-sm text-white/35">{email}</p></div><Link href="/create" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-bold text-black shadow-xl shadow-white/5">Create something <ArrowRight size={16}/></Link></div></div>
   <section className="mt-5 grid gap-4 md:grid-cols-3"><Stat title="Images today" value={usage.images_remaining} suffix="left" note={`${usage.images_used}/10 used today`} icon={<ImageIcon/>} tone="violet"/><Stat title="Videos today" value={usage.videos_remaining} suffix="left" note={`${usage.videos_used}/10 used today`} icon={<Clapperboard/>} tone="fuchsia"/><Stat title="AI Chat" value="∞" suffix="" note="Unlimited conversations" icon={<MessageCircle/>} tone="cyan"/></section>
   <section className="mt-5 grid gap-5 md:grid-cols-[1.05fr_.95fr]"><div className="rounded-[30px] border border-white/10 bg-white/[.03] p-6 md:p-7"><div className="flex items-center justify-between"><div><p className="text-sm font-bold">Your creative activity</p><p className="mt-1 text-xs text-white/30">All-time generated content</p></div><BarChart3 className="text-violet-300" size={19}/></div><div className="mt-7 grid grid-cols-2 gap-4"><div className="rounded-2xl border border-white/5 bg-black/20 p-5"><div className="text-4xl font-black">{counts.image}</div><div className="mt-1 text-xs text-white/30">Images created</div></div><div className="rounded-2xl border border-white/5 bg-black/20 p-5"><div className="text-4xl font-black">{counts.video}</div><div className="mt-1 text-xs text-white/30">Videos created</div></div></div></div><Link href="/chat" className="group rounded-[30px] border border-violet-400/15 bg-gradient-to-br from-violet-500/15 via-fuchsia-500/5 to-transparent p-6 hover:border-violet-400/30 md:p-7"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-400/10"><MessageCircle className="text-violet-200" size={22}/></div><h2 className="mt-5 text-2xl font-black">AI Chat</h2><p className="mt-2 text-sm leading-6 text-white/40">Discuss ideas, analyze images and files, debug code and build projects with your AI assistant.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-violet-200">Open chat <ArrowRight size={15} className="transition-transform group-hover:translate-x-1"/></span></Link></section>
   <section className="mt-5 grid gap-5 md:grid-cols-2"><Link href="/create" className="group rounded-[30px] border border-white/10 bg-gradient-to-br from-violet-500/10 to-cyan-500/[.03] p-7 hover:border-violet-400/25"><div className="flex items-center justify-between"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-violet-400/10"><WandSparkles className="text-violet-200" size={22}/></div><span className="rounded-full border border-white/10 px-3 py-1 text-[10px] text-white/30">FREE</span></div><h2 className="mt-6 text-2xl font-black">AI Creation Studio</h2><p className="mt-2 text-sm leading-6 text-white/40">Generate images and videos with your daily free allowance.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-white/65 group-hover:text-white">Open studio <ArrowRight size={15}/></span></Link><Link href="/creations" className="group rounded-[30px] border border-white/10 bg-white/[.025] p-7 hover:border-cyan-400/20"><div className="text-[10px] font-bold uppercase tracking-[.25em] text-cyan-300">Private library</div><h2 className="mt-6 text-2xl font-black">My creations</h2><p className="mt-2 max-w-md text-sm leading-6 text-white/40">Browse your generated images and videos, with prompts and creation history.</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-white/55 group-hover:text-white">View gallery <ArrowRight size={15}/></span></Link></section>
  </div>
  <div className="fixed bottom-3 left-1/2 z-40 flex -translate-x-1/2 items-center gap-1 rounded-2xl border border-white/10 bg-[#0b0b10]/90 p-1.5 shadow-2xl shadow-black/50 backdrop-blur-xl md:hidden"><Link href="/dashboard" className="rounded-xl bg-white/10 px-4 py-2 text-xs font-semibold text-white">Home</Link><Link href="/create" className="grid h-10 w-10 place-items-center rounded-xl bg-white text-black shadow-lg"><WandSparkles size={17}/></Link><Link href="/chat" className="rounded-xl px-4 py-2 text-xs font-semibold text-white/55">Chat</Link><Link href="/creations" className="rounded-xl px-3 py-2 text-xs font-semibold text-white/55">Library</Link></div>
 </main>
}
function Stat({title,value,suffix,note,icon,tone}:{title:string;value:string|number;suffix:string;note:string;icon:React.ReactNode;tone:"violet"|"fuchsia"|"cyan"}){const cls=tone==="violet"?"border-violet-400/20 bg-violet-500/[.07]":tone==="fuchsia"?"border-fuchsia-400/20 bg-fuchsia-500/[.06]":"border-cyan-400/15 bg-cyan-500/[.045]";return <div className={`rounded-[28px] border p-6 ${cls}`}><div className="flex items-center justify-between"><span className="text-sm text-white/50">{title}</span><span className="text-white/50">{icon}</span></div><div className="mt-6 text-4xl font-black">{value}<span className="ml-2 text-sm font-medium text-white/25">{suffix}</span></div><p className="mt-2 text-xs text-white/30">{note}</p></div>}
